[theme]
base="dark"
primaryColor="#1DB954"
backgroundColor="#121212"
secondaryBackgroundColor="#181818"
textColor="#FFFFFF"
font="sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false